name: Cucumber CI
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout & Setup
        uses: |
          actions/checkout@v2
          uses: actions/setup-node@v2
          
      - name: Cypress run
        run: |
          npm install
          npx cypress run

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with: 
          name: tests-report
          path: report
