name: Cucumber CI
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: npm install
          
      - name: Cypress run
        run: npx cypress run

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with: 
          name: tests-report
          path: report
